{% set name = "requests-kerberos" %}
{% set version = "0.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/requests/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 2846bbca9ed5bd4c12ace11863c63d605684a5d327235ba95ff63b856bfb9e0c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  skip: true # [py<38]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - cryptography >=1.3
    - pyspnego
    - requests >=1.1.0

test:
  imports:
    - requests_kerberos
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/requests/requests-kerberos
  dev_url: https://github.com/requests/requests-kerberos
  doc_url: https://pypi.org/project/requests-kerberos/
  license: ISC
  license_family: MIT
  license_file: LICENSE
  summary: A Kerberos authentication handler for python-requests
  description: |
    Requests is an HTTP library, written in Python, for human beings.
    This library adds optional Kerberos/GSSAPI authentication support
    and supports mutual authentication.

extra:
  recipe-maintainers:
    - duncanmmacleod
